In [1]:
import numpy as np

In [5]:
arr = np.random.rand(3,4)
arr

array([[0.31788189, 0.39686206, 0.61380114, 0.23772091],
       [0.01836891, 0.40029103, 0.48116142, 0.36300518],
       [0.49843511, 0.48082886, 0.80050689, 0.81024479]])

### transpose an array

In [6]:
# the following methods return a copy
print(arr.T)
print()
# or 
print("best")
print(np.transpose(arr)) # best way 
print()
# or
print(arr.transpose())

[[0.31788189 0.01836891 0.49843511]
 [0.39686206 0.40029103 0.48082886]
 [0.61380114 0.48116142 0.80050689]
 [0.23772091 0.36300518 0.81024479]]

best
[[0.31788189 0.01836891 0.49843511]
 [0.39686206 0.40029103 0.48082886]
 [0.61380114 0.48116142 0.80050689]
 [0.23772091 0.36300518 0.81024479]]

[[0.31788189 0.01836891 0.49843511]
 [0.39686206 0.40029103 0.48082886]
 [0.61380114 0.48116142 0.80050689]
 [0.23772091 0.36300518 0.81024479]]


### transpose of a high dimensional array with specified order of axes

In [4]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)

print("-------------------------")
arr1.transpose((1,0,2))
print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
-------------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


### swap axes

In [6]:
arr1 = np.arange(16).reshape((2,2,4))
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [6]:
print(arr1.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


### change the shape of an array

In [15]:
#array : 16 --> 4*4 , 8*2 , 2*4*2
# change the shape of an array and return a copy
arr.reshape((2,6))

ValueError: cannot reshape array of size 3 into shape (2,6)

In [14]:
# arr = [1,2,3] resize(2) -- > 1,2 
# arr = [[2,4,7 ] , [6,4,1 ] ] --> resize --> 2,2 --> [2,4] , [6,4 ]
# change the shape of an array in place
arr.resize((2,6))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

### flatten an array

In [10]:
# return a copy
new = arr.flatten()
new.ndim # number of dimensions

1

In [10]:
# return a view
# change any element in the view will change the initial array
arr.ravel()      

array([0.6341785 , 0.55407741, 0.81189671, 0.90521042, 0.76980015,
       0.54547914, 0.14509388, 0.52098191, 0.21101045, 0.75728602,
       0.3100797 , 0.7699237 ])

### append elements to an array

In [7]:
arr = np.array([1,2,3])

In [8]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [9]:
arr

array([1, 2, 3])

In [10]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


In [11]:
arr

array([1, 2, 3])

### insert elements into an array

In [12]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [13]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [8,2,6])    
print(arr3)

[8 2 6 1 2 3]


In [22]:
arr

array([1, 2, 3])

In [14]:
newarr = np.array([1,3,4])
newarr = np.insert(newarr,0, 5)
newarr

array([5, 1, 3, 4])

### delete elements from an array

In [15]:
arr

array([1, 2, 3])

In [18]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [17]:
arr

array([1, 2, 3])

In [17]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


In [27]:
arr

array([1, 2, 3])

### copy an array

In [19]:
arr = np.array([1,2,3])

In [20]:
arrx = arr

In [21]:
arrx 

array([1, 2, 3])

In [22]:
arrx[0] = 7

In [23]:
arrx

array([7, 2, 3])

In [24]:
arr

array([7, 2, 3])

In [ ]:
#note in c++: 

int x = 3; 
int y = x ; 
y = 4; 
cout << x << endl; // print 3 

# python (numpy ), same in pandas 

In [16]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
a = arr.copy()
# or 
arr1 = np.array(arr, copy=True)