In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [3]:
arr1.shape

(2, 4)

### ```np.concatenate((a, b), axis=0)```

In [4]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [5]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ```np.vstack((a, b))``` 
### ```np.r_[a, b]```

In [6]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [7]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


### ```np.hstack((a, b))```
### ```np.c_[a, b]```

In [8]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [9]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### split an array 

In [10]:
arr = np.random.rand(6,6)
arr

array([[0.15262407, 0.26788224, 0.17578691, 0.05610519, 0.90219075,
        0.99343207],
       [0.23331374, 0.9763724 , 0.69549054, 0.91297765, 0.88022016,
        0.48993793],
       [0.41478353, 0.25231482, 0.57906975, 0.86871821, 0.82381875,
        0.90725826],
       [0.49140541, 0.45645579, 0.91862532, 0.98527217, 0.13416617,
        0.52726631],
       [0.59971821, 0.05751132, 0.03957041, 0.98269629, 0.60551091,
        0.78655947],
       [0.53101073, 0.80242846, 0.04399549, 0.08324299, 0.87295617,
        0.83505251]])

In [11]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[0.15262407, 0.26788224, 0.17578691, 0.05610519, 0.90219075,
        0.99343207],
       [0.23331374, 0.9763724 , 0.69549054, 0.91297765, 0.88022016,
        0.48993793],
       [0.41478353, 0.25231482, 0.57906975, 0.86871821, 0.82381875,
        0.90725826]]), array([[0.49140541, 0.45645579, 0.91862532, 0.98527217, 0.13416617,
        0.52726631],
       [0.59971821, 0.05751132, 0.03957041, 0.98269629, 0.60551091,
        0.78655947],
       [0.53101073, 0.80242846, 0.04399549, 0.08324299, 0.87295617,
        0.83505251]])]


In [12]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[0.86602612, 0.69894752, 0.49505243],
       [0.24290156, 0.15886807, 0.47280521],
       [0.46378562, 0.00900406, 0.81861885],
       [0.93288989, 0.67175988, 0.85892184],
       [0.97087744, 0.10269773, 0.3120645 ],
       [0.56327139, 0.2586936 , 0.06915866]]), array([[0.21722102, 0.2298318 , 0.51544319],
       [0.53718582, 0.89464626, 0.48411814],
       [0.72520995, 0.62621882, 0.71314129],
       [0.45699002, 0.04938953, 0.06811453],
       [0.73021827, 0.50221569, 0.38726495],
       [0.37073569, 0.09986957, 0.62240991]])]
