In [1]:
import numpy as np

### select the unique elements from an array

In [2]:
arr = np.array([7,1,1,2,2,3,3,4,5,6])
print(np.unique(arr))

[1 2 3 4 5 6 7]


In [3]:
arr = np.array([7,1,1,2,2,3,3,4,5,6])
x = arr.tolist()
print(type(arr))
print(type(x))
x

<class 'numpy.ndarray'>
<class 'list'>


[7, 1, 1, 2, 2, 3, 3, 4, 5, 6]

In [4]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)

#print(type(uniques))
print(uniques)
#print(type(counts))
print(counts)

x = int(counts[0])
type(x)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


int

### compute the intersection & union of two arrays

In [5]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [6]:
# intersection
print(np.intersect1d(arr1, arr2))
print(type(np.intersect1d(arr1, arr2)))

[3 4 5]
<class 'numpy.ndarray'>


In [7]:
# union
print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


In [14]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


In [15]:
np.where(arr1 == 3)

(array([2], dtype=int64),)

### compute whether each element of an array is contained in another

In [16]:
print(np.in1d(arr1, arr2))
# arr1=  1 , 2, ,3 ,4, 5 
# arr2 = 3, 4, 5 , 6 , 7

[False False  True  True  True]


In [8]:
# preserve the shape of the array in the output, if the array is of higher dimensions
print(np.isin(arr1, arr2))

[False False  True  True  True]


### compute the elements in an array that are not in another

In [18]:
print(np.setdiff1d(arr2, arr1))

[6 7]


In [19]:
print(np.setdiff1d(arr1, arr2))

[1 2]


### compute the elements in either of two arrays, but not both

In [20]:
print(np.setxor1d(arr1, arr2))

[1 2 6 7]


In [ ]:
1 2 3 4 5 
3 4 5 6 7 