In [1]:
import numpy as np

In [3]:
arr = np.array(range(100)).reshape((10,10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### select an element by row and column indices

In [4]:
print(arr[5][5])
# or more concisely
print(arr[5,5])

55
55


### indexing with slicing

In [6]:
print(arr[1:3, :])

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [5]:
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [5]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(4,2,2)
print(arr)
print("----------------------")
# equivalent to arr[0,:,:,:]
print(arr[0, ...])
print("----------------------")
print(arr[2:,:,:])

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
----------------------
[[0 1]
 [2 3]]
----------------------
[[[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


### assign a scalar to a slice by broadcasting

In [7]:
arr[1:3,:] = 10    # or simply arr[1:3]
arr[:,1:] = 100
print(arr)

[[  0 100 100 100 100 100 100 100 100 100]
 [ 10 100 100 100 100 100 100 100 100 100]
 [ 10 100 100 100 100 100 100 100 100 100]
 [ 30 100 100 100 100 100 100 100 100 100]
 [ 40 100 100 100 100 100 100 100 100 100]
 [ 50 100 100 100 100 100 100 100 100 100]
 [ 60 100 100 100 100 100 100 100 100 100]
 [ 70 100 100 100 100 100 100 100 100 100]
 [ 80 100 100 100 100 100 100 100 100 100]
 [ 90 100 100 100 100 100 100 100 100 100]]


### boolean indexing

In [5]:
arr1 = np.arange(25).reshape((5,5))
print(arr1)
print("----------------------------")
bools = np.array([True, True, False, True, False])
print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
----------------------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [6]:
# negate the condition
print(arr1[~bools])    

[[10 11 12 13 14]
 [20 21 22 23 24]]


In [9]:
arr2 = np.array([1,2,3,4,5])
# multiple conditions
print(arr1[(arr2<2) | (arr2>4)])    

[[ 0  1  2  3  4]
 [20 21 22 23 24]]


### fancy indexing

In [5]:
arr = np.random.rand(10,10)
arr

array([[0.72914795, 0.77688541, 0.72354411, 0.31571154, 0.69764796,
        0.27031191, 0.56594133, 0.92319031, 0.91292307, 0.26138843],
       [0.99839389, 0.26759775, 0.09055392, 0.2746805 , 0.59359897,
        0.49610337, 0.32432384, 0.10624601, 0.83552323, 0.54240808],
       [0.56941984, 0.67985437, 0.74744486, 0.42396772, 0.51222353,
        0.04961441, 0.0042936 , 0.73619697, 0.38689864, 0.16241618],
       [0.61864624, 0.06497909, 0.33238921, 0.40015912, 0.60605332,
        0.99077483, 0.6268479 , 0.8602529 , 0.87139577, 0.00156808],
       [0.14209623, 0.64699634, 0.15781214, 0.09852966, 0.67063419,
        0.62134632, 0.64076474, 0.31680143, 0.31137369, 0.46062845],
       [0.77043066, 0.45784329, 0.06572532, 0.75287356, 0.60493731,
        0.36075159, 0.65626131, 0.7197881 , 0.39401969, 0.12763757],
       [0.77389937, 0.71219108, 0.03777873, 0.46537464, 0.2072386 ,
        0.22519291, 0.6143494 , 0.1788919 , 0.4817561 , 0.45511497],
       [0.08723463, 0.29742413, 0.8731448

In [21]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])       

[0.12644336 0.41499584 0.18881515]


In [12]:
# select rows 3,1,2 and columns 6,4,8 
print(arr[[3,1,2]][:, [6,4,8]])    

[[0.09566854 0.2190723  0.6754328 ]
 [0.28997889 0.13675444 0.07718654]
 [0.15862308 0.45510309 0.94789792]]


### dimension inference

In [13]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(16)).reshape((4,-1))
print(arr.shape)

(4, 4)


### find elements/indices by conditions

In [7]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
# find the elements greater than 5 and return a flattened array
print(arr[x : lambda (x > 5) for x in arr])    # or arr[np.where(arr>5)]

SyntaxError: invalid syntax (<ipython-input-10-783fb9eb14a5>, line 2)

In [28]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
print(np.where(arr>5))

(array([1, 1, 2, 2, 2, 2, 3, 3, 3, 3], dtype=int64), array([1, 1, 0, 0, 1, 1, 0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))


In [30]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10))

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [8]:
# find the indices of the elements on conditions
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]
