In [1]:
import numpy as np

In [2]:
arr = (np.arange(25).reshape(5,5))
np.random.shuffle(arr)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19]])

### sort an array along a specified axis

In [3]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))   

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [4]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19]])

In [5]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [6]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))    

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [6]:
# sort along the column in place
arr.sort(axis=1)    
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [7]:
newarr = np.array([[1,90,54],[23,34,56], [0,10,100]])
newarr =np.sort(newarr)
newarr

array([[  1,  54,  90],
       [ 23,  34,  56],
       [  0,  10, 100]])

In [ ]:
np.something(array)
array.something()
array.differntsyntax

In [8]:
newarr

array([[  1,  54,  90],
       [ 23,  34,  56],
       [  0,  10, 100]])

In [8]:
newarr = newarr.flatten()
newarr

array([  1,  54,  90,  23,  34,  56,   0,  10, 100])

In [9]:
x = np.sort(newarr)
x = x.reshape(3,3)
print(x)

[[  0   1  10]
 [ 23  34  54]
 [ 56  90 100]]


### compute the indices that would sort an array along a specified axis

In [11]:
arr = np.random.rand(5,5)
arr

array([[0.55783203, 0.48807647, 0.34951752, 0.2325411 , 0.48162997],
       [0.03755706, 0.4014756 , 0.82333762, 0.41025353, 0.33971305],
       [0.71833973, 0.64323289, 0.80683779, 0.74461682, 0.55068124],
       [0.96351555, 0.0038118 , 0.53602087, 0.74270261, 0.44554233],
       [0.55509401, 0.46002885, 0.30039879, 0.48373637, 0.83028262]])

In [16]:
# along the row
print(np.argsort(arr, axis=0))

[[0 4 1 1 3]
 [4 2 4 0 0]
 [2 0 3 2 4]
 [3 3 0 4 1]
 [1 1 2 3 2]]


In [9]:
# along the column
print(np.argsort(arr, axis=1))

[[4 3 2 0 1]
 [0 3 1 2 4]
 [3 2 4 0 1]
 [3 4 0 1 2]
 [4 0 1 2 3]]


In [24]:
# if axis=None, return the indices of a flattened array
print(np.argsort(arr, axis=None))

[ 5 20 18 15 23 22 19 13 24 17  0  3  7 12  4  9  2 11  1  8 21 14  6 16
 10]
